name: 'Create release notes'

on: 
  workflow_dispatch:
    inputs:
      change-artifact-dir:
        type: string
        required: true
        default: docs/release-notes/artifacts
        description: The directory where your change artifacts live
      release-output-dir:
        type: string
        required: true
        default: docs/release-notes
        description: The directory where the rendered output will live
      release-artifact-dir:
        type: string
        required: true
        default: docs/release-notes/releases
        description: The directory where your release artifacts live
      common-file:
        type: string
        required: true
        default: docs/release-notes/common.yaml
        description: full path to the YAML file with keys common among all artifacts
      template-dir:
        type: string
        required: true
        default: docs/release-notes/template
        description: directory where your release notes template lives
      template-file-name:
        type: string
        required: true
        default: release-template.md.j2
        description: name of release notes template file
  workflow_call:
    inputs:
      change-artifact-dir:
        type: string
        required: true
        default: docs/release-notes/artifacts
        description: The directory where your change artifacts live
      release-output-dir:
        type: string
        required: true
        default: docs/release-notes
        description: The directory where the rendered output will live
      release-artifact-dir:
        type: string
        required: true
        default: docs/release-notes/releases
        description: The directory where your release artifacts live
      common-file:
        type: string
        required: true
        default: docs/release-notes/common.yaml
        description: full path to the YAML file with keys common among all artifacts
      template-dir:
        type: string
        required: true
        default: docs/release-notes/template
        description: directory where your release notes template lives
      template-file-name:
        type: string
        required: true
        default: release-template.md.j2
        description: name of release notes template file

jobs:
  job1:
    name: 'Generate release notes'
    runs-on: ubuntu-latest

    steps:
      # Checks out repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Sets up Python
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install Python packages
        run: |
          pip install pyyaml
          pip install jinja2
      - name: Generate release notes
        run: |
          python3 build_release_notes.py \
            --artifactdir ${{ inputs.change-artifact-dir }} \
            --outputdir ${{ inputs.release-output-dir }} \
            --releasedir ${{ inputs.release-artifact-dir }} \
            --commonfile ${{ inputs.common-file }} \
            --templatedir ${{ inputs.template-dir }} \
            --templatefile ${{ inputs.template-file-name }}
      - name: Open pull request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ secrets.PAT }}
          commit-message: Add release notes
          branch-name: add-release-notes
          title: Add release notes
          body: |
            Add release notes.

            ### Checklist
            - [ ] The workload version and required software versions were updated.
            - [ ] Additional context was added for relevant updates.
            - [ ] A list of known issues was added.
            - [ ] The release notes were added to the [landing page](docs/release-notes/landing-page.md).
