name: 'Create release notes'

on:
  workflow_dispatch:

env:
  CHANGE_ARTIFACT_DIR: artifacts
  RELEASE_OUTPUT_DIR: docs/release-notes
  RELEASE_ARTIFACT_DIR: releases
  COMMON_FILE: common.yaml
  TEMPLATE_DIR: template
  TEMPLATE_FILE: release-template.md.j2

jobs:
  job1:
    name: 'Generate release notes'
    runs-on: ubuntu-latest

    steps:
      # Checks out repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Sets up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python packages
        run: |
          pip install pyyaml
          pip install jinja2
      - name: Generate release notes
        # TODO: Add RELEASE_TAG to the script
        run: |
          python3 build_release_notes.py --artifactdir $CHANGE_ARTIFACT_DIR --outputdir $RELEASE_OUTPUT_DIR --releasedir $RELEASE_ARTIFACT_DIR --commonfile $COMMON_FILE --templatedir $TEMPLATE_DIR --templatefile $TEMPLATE_FILE
      - name: Open pull request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ secrets.PAT }}
          commit-message: Add release notes
          branch-name: add-release-notes
          title: Add release notes
          body: |
            Add release notes.

            ### Checklist
            - [ ] The workload version and required software versions were updated.
            - [ ] Additional context was added for relevant updates.
            - [ ] A list of known issues was added.
            - [ ] The release notes were added to the [landing page](docs/release-notes/landing-page.md).